-- MySQL Script generated by MySQL Workbench
-- Mon May 20 21:01:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8 ;
USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`_dining_order_combo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`_dining_order_combo` ;

CREATE TABLE IF NOT EXISTS `project`.`_dining_order_combo` (
  `DINING_ORDER_ID` INT NOT NULL,
  `COMBO_ID` INT NOT NULL,
  PRIMARY KEY (`DINING_ORDER_ID`, `COMBO_ID`),
  INDEX `fk_COMBO_ID_idx` (`COMBO_ID` ASC) VISIBLE,
  INDEX `fk_DINING_ORDER_COMBO_ID_idx` (`DINING_ORDER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DINING_ORDER_COMBO_ID`
    FOREIGN KEY (`DINING_ORDER_ID`)
    REFERENCES `project`.`dining_order` (`DINING_ORDER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMBO_ID`
    FOREIGN KEY (`COMBO_ID`)
    REFERENCES `project`.`combo_menu` (`COMBO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`_station_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`_station_line` ;

CREATE TABLE IF NOT EXISTS `project`.`_station_line` (
  `STATION_ID` INT NOT NULL,
  `LINE_ID` INT NOT NULL,
  PRIMARY KEY (`STATION_ID`, `LINE_ID`),
  INDEX `fk_LINE_1_ID_idx` (`LINE_ID` ASC) VISIBLE,
  INDEX `fk_STATION__1_ID_idx` (`STATION_ID` ASC) VISIBLE,
  CONSTRAINT `fk_STATION_1_ID`
    FOREIGN KEY (`STATION_ID`)
    REFERENCES `project`.`station` (`STATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LINE_1_ID`
    FOREIGN KEY (`LINE_ID`)
    REFERENCES `project`.`line` (`LINE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`_station_train_number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`_station_train_number` ;

CREATE TABLE IF NOT EXISTS `project`.`_station_train_number` (
  `STATION_ID` INT NOT NULL,
  `TRAIN_NUMBER_ID` INT NOT NULL,
  `DUPLICATE_STATION_NUM` INT NOT NULL,
  `STATION_ORDER` INT NOT NULL,
  `ARRIVAL_TIME` TIME NULL,
  `DEPARTURE_TIME` TIME NULL,
  `DAY_NUM` INT NOT NULL,
  PRIMARY KEY (`STATION_ID`, `TRAIN_NUMBER_ID`, `DUPLICATE_STATION_NUM`),
  INDEX `fk_TRAIN_NUMBER_1_ID_idx` (`TRAIN_NUMBER_ID` ASC) VISIBLE,
  INDEX `fk_STATION_2_ID_idx` (`STATION_ID` ASC) VISIBLE,
  CONSTRAINT `fk_STATION_2_ID`
    FOREIGN KEY (`STATION_ID`)
    REFERENCES `project`.`station` (`STATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRAIN_NUMBER_1_ID`
    FOREIGN KEY (`TRAIN_NUMBER_ID`)
    REFERENCES `project`.`train_number` (`TRAIN_NUMBER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`_train_number_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`_train_number_line` ;

CREATE TABLE IF NOT EXISTS `project`.`_train_number_line` (
  `TRAIN_NUMBER_ID` INT NOT NULL,
  `LINE_ID` INT NOT NULL,
  PRIMARY KEY (`TRAIN_NUMBER_ID`, `LINE_ID`),
  INDEX `fk_LINE_2_ID_idx` (`LINE_ID` ASC) VISIBLE,
  INDEX `fk_TRAIN_NUMBER_2_idx` (`TRAIN_NUMBER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TRAIN_NUMBER_2_ID`
    FOREIGN KEY (`TRAIN_NUMBER_ID`)
    REFERENCES `project`.`train_number` (`TRAIN_NUMBER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LINE_2_ID`
    FOREIGN KEY (`LINE_ID`)
    REFERENCES `project`.`line` (`LINE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`carriage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`carriage` ;

CREATE TABLE IF NOT EXISTS `project`.`carriage` (
  `CARRIAGE_ID` INT NOT NULL AUTO_INCREMENT,
  `CARRIAGE_NAME` VARCHAR(45) NOT NULL,
  `CARRIAGE_CAPACITY` INT NULL,
  `WHETHER_LAVATORY` TINYINT NULL,
  `WHETHER_DINING_CAR` TINYINT NULL,
  `WHETHER_BERTH` TINYINT NULL,
  `CARRIAGE_CLASS` VARCHAR(45) NULL,
  PRIMARY KEY (`CARRIAGE_ID`),
  UNIQUE INDEX `CARRIAGE_NAME_UNIQUE` (`CARRIAGE_NAME` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`city` ;

CREATE TABLE IF NOT EXISTS `project`.`city` (
  `CITY_ID` INT NOT NULL AUTO_INCREMENT,
  `CITY_NAME` VARCHAR(45) NOT NULL,
  `PROVINCE_ID` INT NULL,
  `SCENERY_ID` INT NULL,
  `SCENERY_NAME` VARCHAR(45) NULL,
  `SOUVENIR_ID` INT NULL,
  `SOUVENIR_NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`CITY_ID`),
  UNIQUE INDEX `CITY_NAME_UNIQUE` (`CITY_NAME` ASC) VISIBLE,
  INDEX `fk_PROVINCE_idx` (`PROVINCE_ID` ASC) VISIBLE,
  INDEX `fk_SCENERY_idx` (`SCENERY_ID` ASC) VISIBLE,
  INDEX `fk_SOUVENIR_idx` (`SOUVENIR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PROVINCE`
    FOREIGN KEY (`PROVINCE_ID`)
    REFERENCES `project`.`province` (`PROVINCE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SCENERY`
    FOREIGN KEY (`SCENERY_ID`)
    REFERENCES `project`.`scenery_category` (`SCENERY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOUVENIR`
    FOREIGN KEY (`SOUVENIR_ID`)
    REFERENCES `project`.`souvenir_catagory` (`SOUVENIR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`combo_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`combo_menu` ;

CREATE TABLE IF NOT EXISTS `project`.`combo_menu` (
  `COMBO_ID` INT NOT NULL AUTO_INCREMENT,
  `COMBO_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COMBO_ID`),
  UNIQUE INDEX `COMBO_NAME_UNIQUE` (`COMBO_NAME` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`dining_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`dining_order` ;

CREATE TABLE IF NOT EXISTS `project`.`dining_order` (
  `DINING_ORDER_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `PURCHASED_ORDER_ID` INT NOT NULL,
  PRIMARY KEY (`DINING_ORDER_ID`),
  INDEX `fk_USER_DINING_ID_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `fk_OERDER_DINING_ID_idx` (`PURCHASED_ORDER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USER_DINING_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `project`.`login_user` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OERDER_DINING_ID`
    FOREIGN KEY (`PURCHASED_ORDER_ID`)
    REFERENCES `project`.`purchased_order` (`PURCHASED_ORDER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`line` ;

CREATE TABLE IF NOT EXISTS `project`.`line` (
  `LINE_ID` INT NOT NULL AUTO_INCREMENT,
  `LINE_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`LINE_ID`),
  UNIQUE INDEX `LINE_NAME_UNIQUE` (`LINE_NAME` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`locomotive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`locomotive` ;

CREATE TABLE IF NOT EXISTS `project`.`locomotive` (
  `LOCOMOTIVE_ID` INT NOT NULL AUTO_INCREMENT,
  `LOCOMOTIVE_NAME` VARCHAR(45) NOT NULL,
  `LOCOMOTIVE_TOP_SPEED` INT NOT NULL,
  PRIMARY KEY (`LOCOMOTIVE_ID`),
  UNIQUE INDEX `LOCOMOTIVE_NAME_UNIQUE` (`LOCOMOTIVE_NAME` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`login_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`login_user` ;

CREATE TABLE IF NOT EXISTS `project`.`login_user` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `USER_PASSWORD` VARCHAR(45) NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`operating_company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`operating_company` ;

CREATE TABLE IF NOT EXISTS `project`.`operating_company` (
  `COMPANY_ID` INT NOT NULL AUTO_INCREMENT,
  `COMPANY_NAME` VARCHAR(45) NOT NULL,
  `COMPANY_CITY_ID` INT NOT NULL,
  PRIMARY KEY (`COMPANY_ID`),
  UNIQUE INDEX `COMPANY_ID_UNIQUE` (`COMPANY_ID` ASC) INVISIBLE,
  UNIQUE INDEX `COMPANY_CITY_ID_UNIQUE` (`COMPANY_CITY_ID` ASC) VISIBLE,
  UNIQUE INDEX `COMPANY_NAME_UNIQUE` (`COMPANY_NAME` ASC) VISIBLE,
  INDEX `NAME_INDEX` (`COMPANY_NAME` ASC) INVISIBLE,
  INDEX `CITY_INDEX` (`COMPANY_CITY_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CITY`
    FOREIGN KEY (`COMPANY_CITY_ID`)
    REFERENCES `project`.`city` (`CITY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`passenger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`passenger` ;

CREATE TABLE IF NOT EXISTS `project`.`passenger` (
  `PASSENGER_ID` INT NOT NULL AUTO_INCREMENT,
  `PASSENGER_NAME` VARCHAR(45) NOT NULL,
  `PASSENGER_CERTIFICATE_NUMBER` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`PASSENGER_ID`),
  UNIQUE INDEX `PASSENGER_ID_NUMBER_UNIQUE` (`PASSENGER_CERTIFICATE_NUMBER` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`province`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`province` ;

CREATE TABLE IF NOT EXISTS `project`.`province` (
  `PROVINCE_ID` INT NOT NULL,
  `PROVINCE_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PROVINCE_ID`),
  UNIQUE INDEX `PROVINCE_ID_UNIQUE` (`PROVINCE_ID` ASC) VISIBLE,
  UNIQUE INDEX `provincecol_UNIQUE` (`PROVINCE_NAME` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`purchased_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`purchased_order` ;

CREATE TABLE IF NOT EXISTS `project`.`purchased_order` (
  `PURCHASED_ORDER_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `PASSENGER_ID` INT NOT NULL,
  `TICKET_ID` INT NOT NULL,
  PRIMARY KEY (`PURCHASED_ORDER_ID`),
  INDEX `fk_USER_ORDER_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `fk_PASSENGER_idx` (`PASSENGER_ID` ASC) VISIBLE,
  INDEX `fk_TICKET_ID_idx` (`TICKET_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USER_ORDER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `project`.`login_user` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PASSENGER_ID`
    FOREIGN KEY (`PASSENGER_ID`)
    REFERENCES `project`.`passenger` (`PASSENGER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TICKET_ID`
    FOREIGN KEY (`TICKET_ID`)
    REFERENCES `project`.`ticket` (`TICKET_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`scenery_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`scenery_category` ;

CREATE TABLE IF NOT EXISTS `project`.`scenery_category` (
  `SCENERY_ID` INT NOT NULL,
  `SCENERY_CLASSIFICATION` VARCHAR(45) NULL,
  PRIMARY KEY (`SCENERY_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`souvenir_catagory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`souvenir_catagory` ;

CREATE TABLE IF NOT EXISTS `project`.`souvenir_catagory` (
  `SOUVENIR_ID` INT NOT NULL,
  `SOUVENIR_CLASSIFICATION` VARCHAR(45) NULL,
  PRIMARY KEY (`SOUVENIR_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`specific_train_number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`specific_train_number` ;

CREATE TABLE IF NOT EXISTS `project`.`specific_train_number` (
  `SPECIFIC_TRAIN_NUMBER_ID` INT NOT NULL AUTO_INCREMENT,
  `TRAIN_NUMBER_ID` INT NOT NULL,
  `TRAIN_CALENDAR_ID` INT NOT NULL,
  `LOCOMOTIVE_ID` INT NULL,
  `CARRIAGE_ID` INT NULL,
  INDEX `fk_CALENDAR_ID_idx` (`TRAIN_CALENDAR_ID` ASC) VISIBLE,
  PRIMARY KEY (`SPECIFIC_TRAIN_NUMBER_ID`),
  INDEX `fk_LOCOMOTIVE_ID_idx` (`LOCOMOTIVE_ID` ASC) VISIBLE,
  INDEX `fk_CARRIAGE_ID_idx` (`CARRIAGE_ID` ASC) VISIBLE,
  INDEX `fk_TRAIN_NUMBER_3_ID_idx` (`TRAIN_NUMBER_ID` ASC) VISIBLE,
  UNIQUE INDEX `SPECIFIC_TRAIN_NUMBER_ID_UNIQUE` (`SPECIFIC_TRAIN_NUMBER_ID` ASC) VISIBLE,
  UNIQUE INDEX `INDEX_1` (`TRAIN_NUMBER_ID` ASC, `TRAIN_CALENDAR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TRAIN_NUNBER_3_ID`
    FOREIGN KEY (`TRAIN_NUMBER_ID`)
    REFERENCES `project`.`train_number` (`TRAIN_NUMBER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CALENDAR_ID`
    FOREIGN KEY (`TRAIN_CALENDAR_ID`)
    REFERENCES `project`.`train_calendar` (`TRAIN_CALENDAR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LOCOMOTIVE_ID`
    FOREIGN KEY (`LOCOMOTIVE_ID`)
    REFERENCES `project`.`locomotive` (`LOCOMOTIVE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARRIAGE_ID`
    FOREIGN KEY (`CARRIAGE_ID`)
    REFERENCES `project`.`carriage` (`CARRIAGE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`station` ;

CREATE TABLE IF NOT EXISTS `project`.`station` (
  `STATION_ID` INT NOT NULL AUTO_INCREMENT,
  `STATION_NAME` VARCHAR(45) NOT NULL,
  `CITY_ID` INT NULL,
  `OPERATING_COMPANY_ID` INT NULL,
  `STATION_CODE` VARCHAR(45) NULL,
  `PINYIN` VARCHAR(45) NULL,
  `PINYIN_CODE` VARCHAR(45) NULL,
  `INITIAL_CODE` VARCHAR(45) NULL,
  `LATITUDE` DOUBLE NULL,
  `LONGTITUDE` DOUBLE NULL,
  PRIMARY KEY (`STATION_ID`),
  INDEX `fk_CITY_ID_idx` (`CITY_ID` ASC) VISIBLE,
  UNIQUE INDEX `STATION_NAME_UNIQUE` (`STATION_NAME` ASC) VISIBLE,
  INDEX `fk_OPERATING_COMPANY_ID_idx` (`OPERATING_COMPANY_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CITY_ID`
    FOREIGN KEY (`CITY_ID`)
    REFERENCES `project`.`city` (`CITY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OPERATING_COMPANY_ID`
    FOREIGN KEY (`OPERATING_COMPANY_ID`)
    REFERENCES `project`.`operating_company` (`COMPANY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`ticket` ;

CREATE TABLE IF NOT EXISTS `project`.`ticket` (
  `TICKET_ID` INT NOT NULL AUTO_INCREMENT,
  `SPECIFIC_TRAIN_NUMBER_ID` INT NOT NULL,
  `STATION_FROM_ID` INT NOT NULL,
  `STATION_TO_ID` INT NOT NULL,
  `STATION_TICKET_LEFT` INT NOT NULL,
  PRIMARY KEY (`TICKET_ID`),
  INDEX `fk_SPECIFIC_TRAIN_UUID_1_idx` (`SPECIFIC_TRAIN_NUMBER_ID` ASC) VISIBLE,
  INDEX `fk_STATION_TO_ID_idx` (`STATION_TO_ID` ASC) VISIBLE,
  INDEX `fk_STATION_FROM_ID_idx` (`STATION_FROM_ID` ASC) VISIBLE,
  UNIQUE INDEX `TICKET_ID_UNIQUE` (`TICKET_ID` ASC) VISIBLE,
  UNIQUE INDEX `INEDX_2` (`SPECIFIC_TRAIN_NUMBER_ID` ASC, `STATION_FROM_ID` ASC, `STATION_TO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_SPECIFIC_TRAIN_NUMBER_ID_1`
    FOREIGN KEY (`SPECIFIC_TRAIN_NUMBER_ID`)
    REFERENCES `project`.`specific_train_number` (`SPECIFIC_TRAIN_NUMBER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STATION_FROM_ID`
    FOREIGN KEY (`STATION_FROM_ID`)
    REFERENCES `project`.`station` (`STATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STATION_TO_ID`
    FOREIGN KEY (`STATION_TO_ID`)
    REFERENCES `project`.`station` (`STATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`train_calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`train_calendar` ;

CREATE TABLE IF NOT EXISTS `project`.`train_calendar` (
  `TRAIN_CALENDAR_ID` INT NOT NULL AUTO_INCREMENT,
  `CALENDAR` DATE NOT NULL,
  `DAY_OF_WEEK` VARCHAR(45) NULL,
  `WHEATHER` VARCHAR(45) NULL,
  PRIMARY KEY (`TRAIN_CALENDAR_ID`),
  UNIQUE INDEX `CALENDAR_UNIQUE` (`CALENDAR` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`train_number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`train_number` ;

CREATE TABLE IF NOT EXISTS `project`.`train_number` (
  `TRAIN_NUMBER_ID` INT NOT NULL AUTO_INCREMENT,
  `TRAIN_NUMBER_NAME` VARCHAR(45) NOT NULL,
  `OPERATING_COMPANY_ID` INT NULL,
  PRIMARY KEY (`TRAIN_NUMBER_ID`),
  UNIQUE INDEX `TRAIN_NUMBER_NAME_UNIQUE` (`TRAIN_NUMBER_NAME` ASC) VISIBLE,
  INDEX `fk_OPERATING_COMPANY_idx` (`OPERATING_COMPANY_ID` ASC) VISIBLE,
  CONSTRAINT `fk_OPERATING_COMPANY`
    FOREIGN KEY (`OPERATING_COMPANY_ID`)
    REFERENCES `project`.`operating_company` (`COMPANY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
